// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ieF-87SKjvUEk9sp7V308RHrU3DEiug',
    appId: '1:389493469464:web:94f4d83456e653f706ae6d',
    messagingSenderId: '389493469464',
    projectId: 'fifa-server-1724b',
    authDomain: 'fifa-server-1724b.firebaseapp.com',
    storageBucket: 'fifa-server-1724b.firebasestorage.app',
    measurementId: 'G-LFYS6E5GY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYQCuE83_NeVloq9pxLdwIBNV_o-1FmxY',
    appId: '1:389493469464:android:3a745604cf3e469606ae6d',
    messagingSenderId: '389493469464',
    projectId: 'fifa-server-1724b',
    storageBucket: 'fifa-server-1724b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCByB7wxsEUyhxriG9FN2xDukhq5jivduI',
    appId: '1:389493469464:ios:8c9f32fc94b9cbc506ae6d',
    messagingSenderId: '389493469464',
    projectId: 'fifa-server-1724b',
    storageBucket: 'fifa-server-1724b.firebasestorage.app',
    iosBundleId: 'com.example.fifaV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCByB7wxsEUyhxriG9FN2xDukhq5jivduI',
    appId: '1:389493469464:ios:8c9f32fc94b9cbc506ae6d',
    messagingSenderId: '389493469464',
    projectId: 'fifa-server-1724b',
    storageBucket: 'fifa-server-1724b.firebasestorage.app',
    iosBundleId: 'com.example.fifaV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7ieF-87SKjvUEk9sp7V308RHrU3DEiug',
    appId: '1:389493469464:web:bb04f60bd759e9df06ae6d',
    messagingSenderId: '389493469464',
    projectId: 'fifa-server-1724b',
    authDomain: 'fifa-server-1724b.firebaseapp.com',
    storageBucket: 'fifa-server-1724b.firebasestorage.app',
    measurementId: 'G-7LSDNEDS85',
  );

}